apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.controller.persistence.size }}
  storageClassName: {{ .Values.controller.persistence.storageClass }}
