apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sonarqube
  labels:
    app: sonarqube
spec:
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: sonarqube
  type: {{ .Values.controller.service.type }}
