# SonarQube configuration
controller:
  image:
    repository: "newimg.azurecr.io/sonarqube-custom"  # Replace with your ACR repository URL
    tag: "latest"  # Replace with the appropriate tag
    pullPolicy: Always
  replicaCount: 1
  
  service:
    type: ClusterIP
    port: 9000
  ingress:
    enabled: false
    name: sonarqube-ingress
    annotations: {}
    path: /
    hosts:
      - sonarqube.local
    tls: []  # Example: tls: [{ hosts: [ "sonarqube.local" ], secretName: "sonarqube-tls" }]
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"
  persistence:
    enabled: true
    storageClass: "default"
    size: "10Gi"


# Database settings (SonarQube can use an external database or internal one)
database:
  external:
    enabled: false
    host: ""
    port: 5432
    user: sonar
    password: sonar_password
    name: sonar

  internal:
    enabled: true  # Use internal Postgres DB
    image:
      repository: postgres
      tag: "13"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
    persistence:
      enabled: true
      storageClass: "standard"
      size: "5Gi"

